### ISSUE TITLE
Readme: question about "start"

### ISSUE THREAD

**Issue by jeroendesloovere** [mlabod/sonos-controller#2]
Hi @mlabod, I want to try the sonos controller.
I installed ```npm install```.
But I'm stuck with:

```bash
webpack
```
Results in
```bash
webpack: command not found
```
And
```bash
electron .
```
Results in 
```bash
electron: command not found
```
Do you know how I can solve it?

Opening the index.html gives me the following javascript error:
![schermafbeelding 2016-02-19 om 14 37 28](https://cloud.githubusercontent.com/assets/588616/13176967/681c7130-d716-11e5-8778-6f47007bba26.png)

**Comment by mlabod** [comment]
@jeroendesloovere 

Hey you would need to install these two globally for now. i should update the Readme.

```shell
npm install -g webpack
npm install -g electron
````

You might need sudo for these.

You also need to add the IP of your sonos player to the `music.js`
There is no auto discovery / ui room switching yet.

Hop that helps.
